### ISSUE TITLE
Arduino Compile Errors for SAMD51 - Adafruit Itsybitsy M4

### ISSUE THREAD

**Issue by kenbiba** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#1]
I am trying to use the I2C Iridium modem with an Itsybitsy M4.

I am getting compile errors for the library attributed to SAMD51 problems.   Help?

```
Arduino: 1.8.13 (Mac OS X), Board: "Adafruit ItsyBitsy M4 (SAMD51), Enabled, 120 MHz (standard), Small (-Os) (standard), 50 MHz (standard), Arduino, Off"

.../Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library-master/src/IridiumSBD.cpp: In member function 'int IridiumSBD::getSystemTime(tm&)':
.../Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library-master/src/IridiumSBD.cpp:237:14: error: aggregate 'tm epoch_start' has incomplete type and cannot be defined
  237 |    struct tm epoch_start;
      |              ^~~~~~~~~~~
...Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library-master/src/IridiumSBD.cpp:257:24: error: 'mktime' was not declared in this scope; did you mean 'mktemp'?
  257 |    time_t epoch_time = mktime(&epoch_start);
      |                        ^~~~~~
      |                        mktemp
.../Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library-master/src/IridiumSBD.cpp:259:16: error: 'localtime' was not declared in this scope
  259 |    memcpy(&tm, localtime(&now), sizeof tm);
      |                ^~~~~~~~~
.../Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library-master/src/IridiumSBD.cpp:259:40: error: invalid application of 'sizeof' to incomplete type 'tm'
  259 |    memcpy(&tm, localtime(&now), sizeof tm);
      |                                        ^~
exit status 1
Error compiling for board Adafruit ItsyBitsy M4 (SAMD51).


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by PaulZC** [comment]
Hi @kenbiba ,
The examples compile OK on Windows using Arduino 1.8.13 and version 1.6.3 of the Adafruit SAMD boards (ItsyBitsy M4).
Your compiler seems to be complaining about the time functions. Do you have an extra time library installed? Maybe that is causing problems?
Best wishes,
Paul

**Comment by adamgarbo** [comment]
Hi @kenbiba,

I suspect that this is related to Paul Stoffegren's Time library. Try renaming `/Arduino/libraries/Time/time.h` to `/Arduino/libraries/Time/time_old.h` and see if you are able to compile.

If that's not the case, I'd suggest posting your code.

Cheers,
Adam
